VIS_KAL0326_PROJEKT/Models/SearchClubsViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace VIS_KAL0326_PROJEKT.Models
{
    public class SearchClubsViewModel
    {
        [StringLength(100, ErrorMessage = "Název klubu nesmí být delší než 100 znaků.")]
        [Display(Name = "Název klubu")]
        public string? Name { get; set; } = string.Empty;

        [StringLength(100, ErrorMessage = "Adresa nesmí být delší než 100 znaků.")]
        [Display(Name = "Adresa")]
        public string? Address { get; set; } = string.Empty;

        [StringLength(50, ErrorMessage = "Typ klubu nesmí být delší než 50 znaků.")]
        [Display(Name = "Typ klubu")]
        public string? Type { get; set; } = string.Empty;

        [Range(1, 1000, ErrorMessage = "Kapacita musí být mezi 1 a 1000.")]
        [Display(Name = "Kapacita")]
        public int? Capacity { get; set; }

        [Range(0, int.MaxValue, ErrorMessage = "Cena od musí být nezáporná.")]
        [Display(Name = "Cena od")]
        public int? PriceFrom { get; set; }

        [Range(0, int.MaxValue, ErrorMessage = "Cena do musí být nezáporná.")]
        [Display(Name = "Cena do")]
        public int? PriceTo { get; set; }

        [Required(ErrorMessage = "Datum rezervace je povinné.")]
        [DataType(DataType.Date, ErrorMessage = "Neplatný formát data.")]
        [Display(Name = "Datum rezervace")]
        public DateTime ReservationDate { get; set; }
    }
}

VIS_KAL0326_PROJEKT/Controllers/ClubController.cs
using Application.Interfaces;
using DataAccess.Interfaces;
using DataAccess.Models;
using Microsoft.AspNetCore.Mvc;
using System.Linq.Expressions;
using System.Reflection.Emit;
using VIS_KAL0326_PROJEKT.Models;

namespace VIS_KAL0326_PROJEKT.Controllers
{
    public class ClubController : Controller
    {
        private readonly IClubService _clubService;

        private readonly ILoginService _loginService;

        public ClubController(IClubService clubService, ILoginService loginService)
        {
            _clubService = clubService;

            _loginService = loginService;
        }

        [HttpGet]
        public IActionResult SearchClubs()
        {
            ViewBag.IsLoggedIn = _loginService.Authorize(Request.Cookies["UserToken"]);

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> SearchClubs(SearchClubsViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            IEnumerable<Club> clubs;
      
            clubs = await _clubService.GetFilteredClubsAsync(model.Name, model.Address, model.Type, model.Capacity, model.PriceFrom, model.PriceTo, model.ReservationDate);
            
            ViewBag.Clubs = clubs;

            var token = Request.Cookies["UserToken"];

            ViewBag.IsLoggedIn = _loginService.Authorize(token);

            ViewBag.UserId = !string.IsNullOrEmpty(token) ? _loginService.ExtractUserIdFromToken(token) : null;

            return View(model);
        }
    }
}

VIS_KAL0326_PROJEKT/Controllers/ReservationController.cs
using Application.Interfaces;
using DataAccess.Interfaces;
using DataAccess.Models;
using Microsoft.AspNetCore.Mvc;
using System.Runtime.CompilerServices;
using VIS_KAL0326_PROJEKT.Models;

namespace VIS_KAL0326_PROJEKT.Controllers
{
    public class ReservationController : Controller
    {
        private readonly IClubService _clubService;

        private readonly IReservationService _reservationService;

        private readonly ILoginService _loginService;

        public ReservationController(IClubService clubService, IReservationService reservationService, ILoginService loginService)
        {
            _reservationService = reservationService;

            _clubService = clubService;

            _loginService = loginService;
        }

        [HttpGet]

        public IActionResult ReviewReservation()
        {
            return RedirectToAction("Login", "Home");
        }

        [HttpPost]
        public async Task<IActionResult> ReviewReservation(int ClubId, int UserId, DateTime ReservationDate)
        {
            var token = Request.Cookies["UserToken"];

            if (!_loginService.Authorize(token))
            {
                ViewBag.IsLoggedIn = false;

                return RedirectToAction("Login", "Home");
            }

            ViewBag.IsLoggedIn = true;

            var club = await _clubService.GetClubByIdAsync(ClubId);

            if (club == null)
            {
                return NotFound("Klub nebyl nalezen.");
            }

            var viewModel = new ReviewReservationViewModel
            {
                ClubId = club.ClubId,
                UserId = UserId,
                ReservationDate = ReservationDate,
                ClubName = club.Name,
                ClubAddress = club.Address,
                ClubType = club.Type,
                ClubCapacity = club.Capacity,
                ClubPricePerPerson = club.Price,
                Price = club.Price
            };

            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> CreateReservation(ReviewReservationViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View("ReviewReservation", model);
            }

            var token = Request.Cookies["UserToken"];

            if (!_loginService.Authorize(token))
            {
                ViewBag.IsLoggedIn = false;

                return RedirectToAction("Login", "Home");
            }

            ViewBag.IsLoggedIn = true;

            var reservation = new Reservation
            {
                ClubId = model.ClubId,
                UserId = model.UserId,
                ReservationDate = model.ReservationDate,
                NumberOfPeople = model.NumberOfPeople,
                Price = model.Price,
                IsConfirmed = false,
                State = "Pending"
            };

            await _reservationService.AddReservationAsync(reservation);

            return Redirect("ListReservations");
        }

        [HttpGet]
        public async Task<IActionResult> ListReservations()
        {
            var token = Request.Cookies["UserToken"];

            if (!_loginService.Authorize(token))
            {
                ViewBag.IsLoggedIn = false;

                return RedirectToAction("Login", "Home");
            }

            ViewBag.IsLoggedIn = true;

            var userId = _loginService.ExtractUserIdFromToken(token);

            var reservations = await _reservationService.GetReservationsByUserIdAsync(userId ?? -1);

            var viewModel = new ListReservationsViewModel
            {
                Reservations = reservations.Select(r => new ReservationItemViewModel
                {
                    ReservationId = r.ReservationId,
                    ClubName = r.Club.Name,
                    ReservationDate = r.ReservationDate,
                    NumberOfPeople = r.NumberOfPeople,
                    State = r.State,
                    Price = r.Price
                }).ToList()
            };

            return View(viewModel);
        }

        [HttpGet]
        public IActionResult PayReservation()
        {
            return RedirectToAction("Login", "Home");
        }

        [HttpPost]
        public async Task<IActionResult> PayReservation(int ReservationId)
        {
            var token = Request.Cookies["UserToken"];

            if (!_loginService.Authorize(token))
            {
                ViewBag.IsLoggedIn = false;

                return RedirectToAction("Login", "Home");
            }

            ViewBag.IsLoggedIn = true;

            var reservation = await _reservationService.GetReservationByIdAsync(ReservationId);

            if (reservation == null)
            {
                return NotFound("Rezervace nebyla nalezena.");
            }

            if (reservation.State != "Confirmed")
            {
                return RedirectToAction("ListReservations");
            }

            var viewModel = new PayReservationViewModel
            {
                ReservationId = reservation.ReservationId,
                ClubName = reservation.Club.Name,
                ReservationDate = reservation.ReservationDate,
                NumberOfPeople = reservation.NumberOfPeople,
                Price = reservation.Price
            };

            return View("PayReservation", viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> ConfirmPayment(PayReservationViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View("PayReservation", model);
            }

            var token = Request.Cookies["UserToken"];

            if (!_loginService.Authorize(token))
            {
                return RedirectToAction("Login", "Home");
            }

            var reservation = await _reservationService.GetReservationByIdAsync(model.ReservationId);

            if (reservation == null)
            {
                return NotFound("Rezervace nebyla nalezena.");
            }

            reservation.State = "Paid";

            await _reservationService.UpdateReservationAsync(reservation);

            return RedirectToAction("ListReservations");
        }

        [HttpPost]

        public async Task<IActionResult> DeleteReservation(int ReservationId    )
        {
            var token = Request.Cookies["UserToken"];

            if (!_loginService.Authorize(token))
            {
                ViewBag.IsLoggedIn = false;

                return RedirectToAction("Login", "Home");
            }

            ViewBag.IsLoggedIn = true;

            await _reservationService.DeleteReservationAsync(ReservationId);

            return RedirectToAction("ListReservations");
        }

    }
}

VIS_KAL0326_PROJEKT/Views/Club/SearchClubs.cshtml
@{
    ViewData["Title"] = "Vyhledat Kluby";

    var clubs = ViewBag.Clubs as IEnumerable<DataAccess.Models.Club>;
}

@model SearchClubsViewModel

<div class="container mt-5">
    <h2 class="text-center">Vyhledat Kluby</h2>

    <form method="post" asp-controller="Club" asp-action="SearchClubs" class="bg-light p-4 rounded shadow-sm">
        @if (ViewBag.ErrorMessage != null)
        {
            <div class="alert alert-danger text-center" role="alert">
                @ViewBag.ErrorMessage
            </div>
        }
        <div class="row">
            <div class="col-md-6 mb-3">
                <label asp-for="Name" class="form-label"></label>

                <input asp-for="Name" class="form-control" placeholder="Zadejte název klubu" />

                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="col-md-6 mb-3">
                <label asp-for="Address" class="form-label"></label>

                <input asp-for="Address" class="form-control" placeholder="Zadejte adresu" />

                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6 mb-3">
                <label asp-for="Type" class="form-label"></label>

                <input asp-for="Type" class="form-control" placeholder="Zadejte typ klubu" />

                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="col-md-6 mb-3">
                <label asp-for="Capacity" class="form-label"></label>

                <input asp-for="Capacity" class="form-control" placeholder="Minimální kapacita" />

                <span asp-validation-for="Capacity" class="text-danger"></span>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6 mb-3">
                <label asp-for="PriceFrom" class="form-label"></label>

                <input asp-for="PriceFrom" class="form-control" placeholder="Minimální cena" />

                <span asp-validation-for="PriceFrom" class="text-danger"></span>
            </div>
            <div class="col-md-6 mb-3">
                <label asp-for="PriceTo" class="form-label"></label>

                <input asp-for="PriceTo" class="form-control" placeholder="Maximální cena" />

                <span asp-validation-for="PriceTo" class="text-danger"></span>
            </div>
        </div>

        <div class="mb-3">
            <div class="mb-3">
                <label asp-for="ReservationDate" class="form-label"></label>

                <input asp-for="ReservationDate" class="form-control"
                       min="@DateTime.Now.ToString("yyyy-MM-dd")" />

                <span asp-validation-for="ReservationDate" class="text-danger"></span>
            </div>
        </div>

        <button type="submit" class="btn btn-primary w-100">Hledat</button>
    </form>
</div>

    @if (clubs != null && clubs.Any())
    {
        <h3 class="mt-5 text-center">Výsledky hledání (@clubs.Count())</h3>

        <table class="table table-striped mt-3 shadow-sm">
            <thead class="table-dark">
                <tr>
                    <th>Název</th>
                    <th>Adresa</th>
                    <th>Typ</th>
                    <th>Kapacita</th>
                    <th>Cena za osobu</th>
                    <th>Rezervovat</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var club in clubs)
                {
                    <tr>
                        <td>@club.Name</td>
                        <td>@club.Address</td>
                        <td>@club.Type</td>
                        <td>@club.Capacity 🧑</td>
                        <td>@club.Price Kč za osobu</td>
                        <td>
                            @if (ViewBag.IsLoggedIn ?? false)
                            {
                                <form method="post" asp-controller="Reservation" asp-action="ReviewReservation" class="d-inline">
                                    <input type="hidden" name="ClubId" value="@club.ClubId" />

                                    <input type="hidden" name="UserId" value="@ViewBag.UserId" />

                                    <input type="hidden" name="ReservationDate" value="@Context.Request.Form["reservationDate"]" />

                                    <button type="submit" class="btn btn-success btn-sm">Rezervovat</button>
                                </form>
                            }
                            else
                            {
                                <span class="text-danger">Nejste přihlášen</span>
                            }
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else if (clubs != null)
    {
        <p class="text-warning text-center mt-4">Nebyly nalezeny žádné kluby odpovídající kritériím.</p>
    }
</div>